<!DOCTYPE html>
<html>
<head>
  <meta charset="utf-8"/>
  <title>Delivery Plugin Example</title>

  <!-- Include the mp-delivery.css styles. -->
  <link rel="stylesheet" href="/css/mp-delivery.css">
  <!-- Include our own custom styles for this project. -->
  <link rel="stylesheet" href="/css/app.css">
</head>
<body>
  <!-- The div that will be used to attach the popup to. -->
  <!-- Can have any id you want. -->
  <div id="delivery-window"></div>

  <!-- The dummy button we are using to open the popup. -->
  <button id="popup-btn">Show Popup</button>

  <!-- A small settings form so you don't have to store your secrets online. -->
  <!-- You can store and retrieve secrets any way you want, we use this only for this example project. -->
  <form id="settings-form">
    <label>
      Google Api Key
      <input type="text" name="maps_key">
    </label>
    <button>Save</button>
  </form>

  <!-- Include the mp-delivery.js script. -->
  <script src="/js/mp-delivery.js"></script>
  <!-- Include our own custom script for this project. -->
  <script src="/js/app.js"></script>
</body>
</html>
